### PR TITLE
Fixes russian weapon names

### PR DESCRIPTION
**Pull request by Kauwgompje**
Changes the weapon names on russian weapons, discussed w/ Mallow & Kauk

### CODE REVIEW

**Comment by Cuel** [comment]
Thoughts: follow BI names?
e.g drop the FP prefix +

`M2 Gun bag`
`M2 Tripod bag`

or
`Dismantled Mk32 GMG (Raised)`
`Dismantled Mk30 HMG`

**Comment by ComfyPillow** [comment]
The FP Prefix is only found on the Backpacks. Reason for this is do they are all well grouped together and more easily recognizable (Same concept as FP_Uniforms).

I Initially did some quick and dirty names since I was focusing more on implementing the actual configs of the bag assembly than the naming semantics (I left that to SuicideZ).

I am going over the backpacks tonight anyway (Author, custom dlc Icon), so I'll discuss this with people who are in teamspeak tonight.

If we had a DLC Icon in Arsenal, then it would make sense to drop the FP Prefix as each backpack would have an icon, indicating that it is indeed associated with FP_Static.

**Comment by Cuel** [comment]
im not entirely sure but I think arsenal uses the "mod.cpp" Icon? from the addon folder

**Comment by ComfyPillow** [comment]
Reading into it, there seems to be 2 ways to pull this off.

The first one being the mod.cpp Icon, but I'm not sure if that gets automatically applied in Arsenal, since I don't remember the Japanese and Chinese Rifle we have in the modpack getting the FP Icon.

The other one would be to create a new entry in the CfgMods class, and then in the weapon bags, add the following entry:

``` cpp
dlc = "CfgModsClassName"
```

But yeah, if the mod.cpp way works, I'll go with that.

**Comment by Kauwgompje** [comment]
So, let's change the names to vanilla standard, but keep the FP prefix on the bags?

**Pull request merged**
